
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-08-07T10:33:53-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "65b8624cbd5fe7bcf1bd87b27b7e830cc9bb56eb",
 "version": "2.42.1rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
