# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: synapse_pb/actuators.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from synapse_pb import timestamp_pb2 as synapse__pb_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='synapse_pb/actuators.proto',
  package='synapse_pb',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1asynapse_pb/actuators.proto\x12\nsynapse_pb\x1a\x1asynapse_pb/timestamp.proto\"i\n\tActuators\x12$\n\x05stamp\x18\x01 \x01(\x0b\x32\x15.synapse_pb.Timestamp\x12\x10\n\x08position\x18\x02 \x03(\x01\x12\x10\n\x08velocity\x18\x03 \x03(\x01\x12\x12\n\nnormalized\x18\x04 \x03(\x01\x62\x06proto3'
  ,
  dependencies=[synapse__pb_dot_timestamp__pb2.DESCRIPTOR,])




_ACTUATORS = _descriptor.Descriptor(
  name='Actuators',
  full_name='synapse_pb.Actuators',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='stamp', full_name='synapse_pb.Actuators.stamp', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='position', full_name='synapse_pb.Actuators.position', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='velocity', full_name='synapse_pb.Actuators.velocity', index=2,
      number=3, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='normalized', full_name='synapse_pb.Actuators.normalized', index=3,
      number=4, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=175,
)

_ACTUATORS.fields_by_name['stamp'].message_type = synapse__pb_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['Actuators'] = _ACTUATORS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Actuators = _reflection.GeneratedProtocolMessageType('Actuators', (_message.Message,), {
  'DESCRIPTOR' : _ACTUATORS,
  '__module__' : 'synapse_pb.actuators_pb2'
  # @@protoc_insertion_point(class_scope:synapse_pb.Actuators)
  })
_sym_db.RegisterMessage(Actuators)


# @@protoc_insertion_point(module_scope)
