
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-08-09T00:10:30-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "153b3a76b2df550cf23b821742daa11c0ad3974e",
 "version": "0.2.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
