# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import typing_extensions

from .report_anthropic_request_req_payload_zero_messages_item_content_item_image import (
    ReportAnthropicRequestReqPayloadZeroMessagesItemContentItemImage,
)
from .report_anthropic_request_req_payload_zero_messages_item_content_item_text import (
    ReportAnthropicRequestReqPayloadZeroMessagesItemContentItemText,
)


class ReportAnthropicRequestReqPayloadZeroMessagesItemContentItem_Text(
    ReportAnthropicRequestReqPayloadZeroMessagesItemContentItemText
):
    type: typing_extensions.Literal["text"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class ReportAnthropicRequestReqPayloadZeroMessagesItemContentItem_Image(
    ReportAnthropicRequestReqPayloadZeroMessagesItemContentItemImage
):
    type: typing_extensions.Literal["image"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


ReportAnthropicRequestReqPayloadZeroMessagesItemContentItem = typing.Union[
    ReportAnthropicRequestReqPayloadZeroMessagesItemContentItem_Text,
    ReportAnthropicRequestReqPayloadZeroMessagesItemContentItem_Image,
]
