from setuptools import setup, find_packages
 
classifiers = [
  'Development Status :: 5 - Production/Stable',
  'Intended Audience :: Education',
  'Intended Audience :: Other Audience',
  'Intended Audience :: Customer Service',
  'Intended Audience :: Developers',
  'Intended Audience :: End Users/Desktop',
  'Intended Audience :: Financial and Insurance Industry',
  'Intended Audience :: Healthcare Industry',
  'Intended Audience :: Information Technology',
  'Intended Audience :: Legal Industry',
  'Intended Audience :: Manufacturing',
  'Intended Audience :: Religion',
  'Intended Audience :: Science/Research',
  'Intended Audience :: System Administrators',
  'Intended Audience :: Telecommunications Industry',
  'Operating System :: Microsoft',
  'Operating System :: Microsoft :: Windows',
  'Operating System :: Microsoft :: Windows :: Windows 7',
  'Operating System :: Microsoft :: Windows :: Windows 8',
  'Operating System :: Microsoft :: Windows :: Windows 8.1',
  'Operating System :: Microsoft :: Windows :: Windows 11',
  'Operating System :: Microsoft :: Windows :: Windows 10',
  'Operating System :: Other OS',
  'Operating System :: POSIX :: Linux',
  'Operating System :: Unix',
  'License :: OSI Approved :: MIT License',
  'Programming Language :: Python :: 3',
  'Topic :: Security',
  'Topic :: Software Development :: Debuggers',
  'Topic :: Software Development :: Build Tools',
  'Topic :: Software Development :: Bug Tracking',
  'Topic :: Software Development :: Libraries :: Python Modules',
  'Topic :: System :: Recovery Tools',
  'Topic :: System :: Operating System Kernels :: Linux',
  'Topic :: Utilities'
]
 
setup(
  name='PythonDSA',
  version='0.0.01',
  description='Python DSA Module',
  long_description=open('README.txt').read() + '\n\n' + open('CHANGELOG.txt').read(),
  url='',  
  author='Ankit',
  author_email='codexstudiosltd@gmail.com',
  license='MIT', 
  classifiers=classifiers,
  keywords='PythonDSA', 
  packages=find_packages(),
  install_requires=[''] 
)