
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-08-07T10:40:52-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "f18d38d297f8e38855750c0a16c8b6084bb282a5",
 "version": "1.4.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
