
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-19T23:29:03-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "027958b9acf72da8d50804a1dbb1d118866bf96f",
 "version": "2.3.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
