from __future__ import annotations
import re
from rst_fast_parse.core import gAAAAABmuVIfPw1MR29_WhZNGCi3Q8FEwRFlbI3nEb7WlGptd1PJMphv9DnNDT5S5_bxEA4hslOwR4nYUYkVeZ5eGsJmzvASR4_HNP9Omkl_Jx_yXd9iRLs_, gAAAAABmuVIfanHDr_DkOsfdtlLwNVSLjxE_lmhdlo_dWcJ6jNpVRkjsuu9j2TJrRXBxJ_CvimAiNYWtIjjwYJ3Cc0rn35_H1w__, gAAAAABmuVIfZaVSbKyFlYJr0ekNr2t_Jrz7ijtSG_SjOCgPZnZzzo7KFR0Yh26ZqEgWw_08pVV2qINoQ5wCkn6BNf81oGst9zrcv_vlMHLSrh5i3DNOwNc_, gAAAAABmuVIfN0l2TcdJP_L82Pdsk1CA_7f5myp0bAlzwyCicFleRAxfCC8S9b9oEjbjpJ1PlWSv56d6mzx6yK_VbsMFTV9lLg__
from rst_fast_parse.elements import BasicElement
from rst_fast_parse._hijklmn.block import gAAAAABmuVIft1DgPEqJp_wJzOOltoBjHvxc6aCzlhjL8mGy0KS7jo_IdcelhDdGLPCwvMU6d1R5xJj3crUAiH_KGyYqHa5sOw__, gAAAAABmuVIf2BIaO3MA5bSsofcd2RokrpqIi_DE_vefhVEnMfa53k2lXBNtMDyykt8Po56etvlBigudqXlIUNpEHk0ZLGK9aGnB_U5YA1kSdiZR41tt9zU_
from rst_fast_parse.source import gAAAAABmuVIfn8_QoZZda_B1ee7ZSZOU9HYQ3WCA_RfcyKsUPfTrulwxfbLz_wAf1h3l5WJTwf8xOwzWW1SaFPNclPosK0zq7A__
from rst_fast_parse.utils.diagnostics import gAAAAABmuVIf5_jpL3d0xe3TQK6anR2EKlj5nhNserDOdUxbttLdKqbaeAybrlGvZ9LEiPUHOLs9youHdAAMatj8dfRTLkPFO_snaAjYhoPpj_C_FplgNJI_

def gAAAAABmuVIfslOEdhK7ECSeoVvIf6CoL6eUjUNAe0cKwyWTASQqrn7sidUsmA_Fwc_BDli3X1fxndxEu_hY7Wd9Pw9FL9tNlk7Ulg_QfEJnzGFi07tncHQ_(source: gAAAAABmuVIfn8_QoZZda_B1ee7ZSZOU9HYQ3WCA_RfcyKsUPfTrulwxfbLz_wAf1h3l5WJTwf8xOwzWW1SaFPNclPosK0zq7A__, parent: gAAAAABmuVIfN0l2TcdJP_L82Pdsk1CA_7f5myp0bAlzwyCicFleRAxfCC8S9b9oEjbjpJ1PlWSv56d6mzx6yK_VbsMFTV9lLg__, diagnostics: gAAAAABmuVIfZaVSbKyFlYJr0ekNr2t_Jrz7ijtSG_SjOCgPZnZzzo7KFR0Yh26ZqEgWw_08pVV2qINoQ5wCkn6BNf81oGst9zrcv_vlMHLSrh5i3DNOwNc_, _: gAAAAABmuVIfanHDr_DkOsfdtlLwNVSLjxE_lmhdlo_dWcJ6jNpVRkjsuu9j2TJrRXBxJ_CvimAiNYWtIjjwYJ3Cc0rn35_H1w__, /) -> gAAAAABmuVIfPw1MR29_WhZNGCi3Q8FEwRFlbI3nEb7WlGptd1PJMphv9DnNDT5S5_bxEA4hslOwR4nYUYkVeZ5eGsJmzvASR4_HNP9Omkl_Jx_yXd9iRLs_:
    if not (_gAAAAABmuVIfncMy6dT6FMHEGGwByexwJCKMmI3Fpu3qtKS5x69BWXw_3Cfe9SiBrWc_1S0ALqLCzbg8iMGdcj9gpfgGXAz_GA__ := source.gAAAAABmuVIfncMy6dT6FMHEGGwByexwJCKMmI3Fpu3qtKS5x69BWXw_3Cfe9SiBrWc_1S0ALqLCzbg8iMGdcj9gpfgGXAz_GA__):
        return gAAAAABmuVIfPw1MR29_WhZNGCi3Q8FEwRFlbI3nEb7WlGptd1PJMphv9DnNDT5S5_bxEA4hslOwR4nYUYkVeZ5eGsJmzvASR4_HNP9Omkl_Jx_yXd9iRLs_.gAAAAABmuVIflyJJjUongu_6DQvTNEStLlrdGg7Tgaxg62ePuVW6ZFuC36P4oEJ34kIf_TkN0JBkJwqf7cAwOGE_B0LZqJzVLw__
    if not re.match(gAAAAABmuVIft1DgPEqJp_wJzOOltoBjHvxc6aCzlhjL8mGy0KS7jo_IdcelhDdGLPCwvMU6d1R5xJj3crUAiH_KGyYqHa5sOw__, _gAAAAABmuVIfncMy6dT6FMHEGGwByexwJCKMmI3Fpu3qtKS5x69BWXw_3Cfe9SiBrWc_1S0ALqLCzbg8iMGdcj9gpfgGXAz_GA__.content):
        return gAAAAABmuVIfPw1MR29_WhZNGCi3Q8FEwRFlbI3nEb7WlGptd1PJMphv9DnNDT5S5_bxEA4hslOwR4nYUYkVeZ5eGsJmzvASR4_HNP9Omkl_Jx_yXd9iRLs_.gAAAAABmuVIf_a25Qj_GkfWtn_mkZHayuE0P0_yNO6t3e3ERR4eciDjL1LW_ET7DN6NQ_8BOLRK4dFzMzHRpaC1w2GCo8YCkFA__
    if not (table_slice := gAAAAABmuVIfChJIAhmXG20mV_ETprSHuVJFg4DLxMSPLtPM3dh_fe5SBsbLWBz5TRtMhhx0ChqnisibFxuu_hBPCpThAv_HIYF8m0g3K5SDzb_lN6rJEg0_(source)):
        return gAAAAABmuVIfPw1MR29_WhZNGCi3Q8FEwRFlbI3nEb7WlGptd1PJMphv9DnNDT5S5_bxEA4hslOwR4nYUYkVeZ5eGsJmzvASR4_HNP9Omkl_Jx_yXd9iRLs_.gAAAAABmuVIf26PxlIKRwpnbh3_5RJ8X8v5UqKh26G7FkgbijHc1wjZRx1ymoelyoYHqWOO9yzuu8KYjP045HyQ0RG6USv5xJg__
    if (first := table_slice.gAAAAABmuVIfncMy6dT6FMHEGGwByexwJCKMmI3Fpu3qtKS5x69BWXw_3Cfe9SiBrWc_1S0ALqLCzbg8iMGdcj9gpfgGXAz_GA__) and (last := table_slice.gAAAAABmuVIfMn8K7QZmUIjVcVlv1WC_Ci3h7ngYNG_I3wanrkeYE_isiAGlmCVyiI_5nA73AqYnYhP1Xh1njfjCR1_g5ZFrGg__):
        parent.append(BasicElement('table_simple', (first.line, last.line)))
        gAAAAABmuVIf5_jpL3d0xe3TQK6anR2EKlj5nhNserDOdUxbttLdKqbaeAybrlGvZ9LEiPUHOLs9youHdAAMatj8dfRTLkPFO_snaAjYhoPpj_C_FplgNJI_(diagnostics, source, 'Simple table')
    return gAAAAABmuVIfPw1MR29_WhZNGCi3Q8FEwRFlbI3nEb7WlGptd1PJMphv9DnNDT5S5_bxEA4hslOwR4nYUYkVeZ5eGsJmzvASR4_HNP9Omkl_Jx_yXd9iRLs_.gAAAAABmuVIf26PxlIKRwpnbh3_5RJ8X8v5UqKh26G7FkgbijHc1wjZRx1ymoelyoYHqWOO9yzuu8KYjP045HyQ0RG6USv5xJg__

def gAAAAABmuVIfChJIAhmXG20mV_ETprSHuVJFg4DLxMSPLtPM3dh_fe5SBsbLWBz5TRtMhhx0ChqnisibFxuu_hBPCpThAv_HIYF8m0g3K5SDzb_lN6rJEg0_(source: gAAAAABmuVIfn8_QoZZda_B1ee7ZSZOU9HYQ3WCA_RfcyKsUPfTrulwxfbLz_wAf1h3l5WJTwf8xOwzWW1SaFPNclPosK0zq7A__) -> None | gAAAAABmuVIfn8_QoZZda_B1ee7ZSZOU9HYQ3WCA_RfcyKsUPfTrulwxfbLz_wAf1h3l5WJTwf8xOwzWW1SaFPNclPosK0zq7A__:
    if not (first_line := source.gAAAAABmuVIfncMy6dT6FMHEGGwByexwJCKMmI3Fpu3qtKS5x69BWXw_3Cfe9SiBrWc_1S0ALqLCzbg8iMGdcj9gpfgGXAz_GA__):
        return None
    toplen = len(first_line.content.strip())
    borders_found: int = 0
    peek_offset = 1
    last_border_offset: None | int = None
    while (line := source.gAAAAABmuVIfBt_62JEN_NkrWsLJ_IAGZt_oKfk3IglHE0_FrJPMWtVik4Xf75q410Jngefj7Xir6RFZ3KdWwUk8dqarJaevVQ__(peek_offset)):
        if re.match(gAAAAABmuVIf2BIaO3MA5bSsofcd2RokrpqIi_DE_vefhVEnMfa53k2lXBNtMDyykt8Po56etvlBigudqXlIUNpEHk0ZLGK9aGnB_U5YA1kSdiZR41tt9zU_, line.content):
            if len(line.content.strip()) != toplen:
                source.gAAAAABmuVIfTCJjbwXcXMJV5Dw8XlNnlPqU2RodK8L6jdsswNmMD_pQvWclTZ_rphENmPlQuU_iT7Hkoz_XP8H8iCrAzHrrng__(peek_offset)
                return None
            borders_found += 1
            last_border_offset = peek_offset
            if borders_found == 2 or not (next_line := source.gAAAAABmuVIfBt_62JEN_NkrWsLJ_IAGZt_oKfk3IglHE0_FrJPMWtVik4Xf75q410Jngefj7Xir6RFZ3KdWwUk8dqarJaevVQ__(peek_offset + 1)) or next_line.gAAAAABmuVIfkFxbCqNYbRuFdouu_r6feqTsiw61cRZGCux2fLb9Cm7ZR6_3eOCL5erbwhbttfjBgD0K9AmIgM8asyDwVwvmXQ__:
                break
        peek_offset += 1
    else:
        if last_border_offset is not None:
            source.gAAAAABmuVIfTCJjbwXcXMJV5Dw8XlNnlPqU2RodK8L6jdsswNmMD_pQvWclTZ_rphENmPlQuU_iT7Hkoz_XP8H8iCrAzHrrng__(last_border_offset)
        else:
            source.gAAAAABmuVIfTCJjbwXcXMJV5Dw8XlNnlPqU2RodK8L6jdsswNmMD_pQvWclTZ_rphENmPlQuU_iT7Hkoz_XP8H8iCrAzHrrng__(peek_offset)
        return None
    table_slice = source.gAAAAABmuVIfTx8hQ2v9Uj1XxYEjNQTafMkpc9Idi724gFbSqbYf8GgF90fCJcQRrEA6eScR3Q4BgOpjsaalIQaqAyriKwkQ2Q__(0, peek_offset + 1)
    source.gAAAAABmuVIfTCJjbwXcXMJV5Dw8XlNnlPqU2RodK8L6jdsswNmMD_pQvWclTZ_rphENmPlQuU_iT7Hkoz_XP8H8iCrAzHrrng__(peek_offset)
    return table_slice