# Autogenerated by devscripts/update-version.py

__version__ = '2024.08.06.232802'

RELEASE_GIT_HEAD = 'a065086640e888e8d58c615d52ed2f4f4e4c9d18'

VARIANT = 'pip'

UPDATE_HINT = 'You installed yt-dlp with pip or using the wheel from PyPi; Use that to update'

CHANNEL = 'nightly'

ORIGIN = 'yt-dlp/yt-dlp-nightly-builds'

_pkg_version = '2024.08.06.232802dev'
