# coding: utf-8

"""
    Odin

    ODIN APIs to search across IP Services, CVEs, Certificates, Exposed Files/Buckets, Domains and more  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ServiceFullCveData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'score': 'float',
        'severity': 'str'
    }

    attribute_map = {
        'id': 'id',
        'score': 'score',
        'severity': 'severity'
    }

    def __init__(self, id=None, score=None, severity=None):  # noqa: E501
        """ServiceFullCveData - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._score = None
        self._severity = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if score is not None:
            self.score = score
        if severity is not None:
            self.severity = severity

    @property
    def id(self):
        """Gets the id of this ServiceFullCveData.  # noqa: E501


        :return: The id of this ServiceFullCveData.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ServiceFullCveData.


        :param id: The id of this ServiceFullCveData.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def score(self):
        """Gets the score of this ServiceFullCveData.  # noqa: E501


        :return: The score of this ServiceFullCveData.  # noqa: E501
        :rtype: float
        """
        return self._score

    @score.setter
    def score(self, score):
        """Sets the score of this ServiceFullCveData.


        :param score: The score of this ServiceFullCveData.  # noqa: E501
        :type: float
        """

        self._score = score

    @property
    def severity(self):
        """Gets the severity of this ServiceFullCveData.  # noqa: E501


        :return: The severity of this ServiceFullCveData.  # noqa: E501
        :rtype: str
        """
        return self._severity

    @severity.setter
    def severity(self, severity):
        """Sets the severity of this ServiceFullCveData.


        :param severity: The severity of this ServiceFullCveData.  # noqa: E501
        :type: str
        """

        self._severity = severity

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ServiceFullCveData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ServiceFullCveData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
