
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-08-09T10:35:10-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "f6bebfcab38a0850715cc46f24f435067c85b96c",
 "version": "2.20.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
