# coding: utf-8

"""
    Odin

    ODIN APIs to search across IP Services, CVEs, Certificates, Exposed Files/Buckets, Domains and more  # noqa: E501

    OpenAPI spec version: 1.0

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import odin
from odin.models.certificate_certificate_hash_response_data import CertificateCertificateHashResponseData  # noqa: E501
from odin.rest import ApiException


class TestCertificateCertificateHashResponseData(unittest.TestCase):
    """CertificateCertificateHashResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCertificateCertificateHashResponseData(self):
        """Test CertificateCertificateHashResponseData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = odin.models.certificate_certificate_hash_response_data.CertificateCertificateHashResponseData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
