from __future__ import annotations
import re
from rst_fast_parse._abcdefg.ffffffff import gAAAAABmuVIfL6S_WUQghhEW0QkiixHkVsG_of2gxN1JEJ7mwq3Kz58VNgm6frgxTms7Q_D8_U4SAQlENE3x9XI2zASbCstMd1qTYd9vDJUWZivSb7cOPp4_
from rst_fast_parse._abcdefg.mmmmmmmm import gAAAAABmuVIfwSuSLuNlfhJILAE8nn29di16uG_ahL3G_ocOwj3GMSnYAZ0a5_bakiwCve3QIR_6NgmEdnBPUcP8Ax7fCbLPOJgykTNwDeVm_vsJtOsQi6k_
from rst_fast_parse._abcdefg.jjjjjjjj import gAAAAABmuVIf67_BChxb2vWsL_oxhJ3lhmq8cHOePsvQjY36pOe7nLmQ_WQAcx0hAdflHVI94q5g2dayIrvokRire0xQ0nXj3UxVVVWyT5517247HZ3t_zI_
from rst_fast_parse._abcdefg.bbbbbbbb import gAAAAABmuVIfPlr__na8C_wq3KoS8rhM1Pkp3Wz5iBOVili0l6C33SIEJbmFbX1SNenvkGmeBwqf87NXHExi04FJEh3L_M4JNq0CkbHOTzPXU_Oej1aZVGw_
from rst_fast_parse._abcdefg.cccccccc import gAAAAABmuVIfNSIxWbCb7YskF8JAbjWEUoUbFaDQuF2bZofvBUAolj1EpIIDIKPCHhKw6GnRUiiKFoTftnLsXDskvsYStjJmdcCSGEB_CUA5D9IzMK_CN90_
from rst_fast_parse._abcdefg.hhhhhhhh import gAAAAABmuVIfa3vfUUSnPxu14e_fA6NKN2N0wSHOVNS7YnDYNCWutsKzUBU8ZR5M0PNxKuQyhoUukvAYH9i8LdqaL6LqoHBp2puLqS_MZ8POwJbhHL9Srak_
from rst_fast_parse._abcdefg.llllllll import gAAAAABmuVIfBLrQ6OjgV7NN34yk474n9rq7lnCn_LW0KJSw3y_uiL6hXiz5gHHBXguGwDjJv632DzftlBTkPV_w1VbqXDYUL5gJyXkF68Ld4g3aZTbluWw_
from rst_fast_parse._abcdefg.nnnnnnnn import gAAAAABmuVIfcJJ36pcvWvwZ4AvUrDnMqNaJjQhhOL73MngXzH5gCexj5ACCAiwJ6ZBYbf8xO_fGQ63WLtfgLJ3zkdAw117zBQ__
from rst_fast_parse._abcdefg.gggggggg import gAAAAABmuVIfUfOpf3C4xgenepvRKIbdDncTGlYX5qsScBiriXzHrnEQdv8X5ofH52bz6dwtQo0GQBJG0_gYxdyevu8Vs_bomtBXbNorpJntRIVGci8rWOg_
from rst_fast_parse._abcdefg.aaaaaaaa import gAAAAABmuVIf9f5px0ON_x5fD0cwgqRlEVPSB_hyOwJCEHdI_HSX7HPxFKOwJZGqBBHJea5gGIKd69A9_jl5pT9U_2KgLOqjarA8LgC4mOeF0rKT8_sMCG8_
from rst_fast_parse._abcdefg.eeeeeeee import gAAAAABmuVIffftG1vYYb9Xriv_NpU8cL2PAIYxWM0pIyYB99BLjhrvaXiXKn4ny7BC7yqsxYvcRChoXqHz2eVdAJ9dNV2EKWgxiAau2eyA7sp_WZ3bZ_p4_
from rst_fast_parse._abcdefg.iiiiiiii import gAAAAABmuVIfR5O0hq_TeRl2z4L_AOBo1v3MJl6VeG2Mz1R4MVDMJQlFFlg9PSth93A__ZOeu5bAqA57QNkqtn7XH5wAx85qAQJkq65nY4dPrOmV1iDUBJc_
from rst_fast_parse._abcdefg.dddddddd import gAAAAABmuVIfgGi48U3hIUtP_tZPwH79j1lU9U4OOzX5aHWp3RjLywVg51Wpx1PKUDZFHoCOv28_6x186MJlbqUGcvupPm0NIfVuXt8yJcg_LD06hg6HcqI_
from rst_fast_parse._abcdefg.kkkkkkkk import gAAAAABmuVIfslOEdhK7ECSeoVvIf6CoL6eUjUNAe0cKwyWTASQqrn7sidUsmA_Fwc_BDli3X1fxndxEu_hY7Wd9Pw9FL9tNlk7Ulg_QfEJnzGFi07tncHQ_
from rst_fast_parse.core import gAAAAABmuVIfVha6G67z1s3rWuXlPoPJXCwGHxsniKYepTcKKbezeqqSvz_VXAD6OzGW_vQTK5qHtCT1j9KFZU_ujzcT2sf2MQ__, gAAAAABmuVIfanHDr_DkOsfdtlLwNVSLjxE_lmhdlo_dWcJ6jNpVRkjsuu9j2TJrRXBxJ_CvimAiNYWtIjjwYJ3Cc0rn35_H1w__
from rst_fast_parse.diagnostics import DiagnosticList
from rst_fast_parse.elements import ElementListBase
from rst_fast_parse.source import gAAAAABmuVIf9wRDJEScCUZq7RJd1lzU5Co9Q9qvdG39lzIABLH4JrYQUo0X7VYcijVx1kQa6sabviTFht6T3drJd4h3rsG6TA__, gAAAAABmuVIfn8_QoZZda_B1ee7ZSZOU9HYQ3WCA_RfcyKsUPfTrulwxfbLz_wAf1h3l5WJTwf8xOwzWW1SaFPNclPosK0zq7A__
_DEFAULT_BLOCK_PARSERS: tuple[gAAAAABmuVIfVha6G67z1s3rWuXlPoPJXCwGHxsniKYepTcKKbezeqqSvz_VXAD6OzGW_vQTK5qHtCT1j9KFZU_ujzcT2sf2MQ__, ...] = (gAAAAABmuVIfwSuSLuNlfhJILAE8nn29di16uG_ahL3G_ocOwj3GMSnYAZ0a5_bakiwCve3QIR_6NgmEdnBPUcP8Ax7fCbLPOJgykTNwDeVm_vsJtOsQi6k_, gAAAAABmuVIf67_BChxb2vWsL_oxhJ3lhmq8cHOePsvQjY36pOe7nLmQ_WQAcx0hAdflHVI94q5g2dayIrvokRire0xQ0nXj3UxVVVWyT5517247HZ3t_zI_, gAAAAABmuVIfPlr__na8C_wq3KoS8rhM1Pkp3Wz5iBOVili0l6C33SIEJbmFbX1SNenvkGmeBwqf87NXHExi04FJEh3L_M4JNq0CkbHOTzPXU_Oej1aZVGw_, gAAAAABmuVIfa3vfUUSnPxu14e_fA6NKN2N0wSHOVNS7YnDYNCWutsKzUBU8ZR5M0PNxKuQyhoUukvAYH9i8LdqaL6LqoHBp2puLqS_MZ8POwJbhHL9Srak_, gAAAAABmuVIfUfOpf3C4xgenepvRKIbdDncTGlYX5qsScBiriXzHrnEQdv8X5ofH52bz6dwtQo0GQBJG0_gYxdyevu8Vs_bomtBXbNorpJntRIVGci8rWOg_, gAAAAABmuVIfR5O0hq_TeRl2z4L_AOBo1v3MJl6VeG2Mz1R4MVDMJQlFFlg9PSth93A__ZOeu5bAqA57QNkqtn7XH5wAx85qAQJkq65nY4dPrOmV1iDUBJc_, gAAAAABmuVIfNSIxWbCb7YskF8JAbjWEUoUbFaDQuF2bZofvBUAolj1EpIIDIKPCHhKw6GnRUiiKFoTftnLsXDskvsYStjJmdcCSGEB_CUA5D9IzMK_CN90_, gAAAAABmuVIf9f5px0ON_x5fD0cwgqRlEVPSB_hyOwJCEHdI_HSX7HPxFKOwJZGqBBHJea5gGIKd69A9_jl5pT9U_2KgLOqjarA8LgC4mOeF0rKT8_sMCG8_, gAAAAABmuVIfgGi48U3hIUtP_tZPwH79j1lU9U4OOzX5aHWp3RjLywVg51Wpx1PKUDZFHoCOv28_6x186MJlbqUGcvupPm0NIfVuXt8yJcg_LD06hg6HcqI_, gAAAAABmuVIfslOEdhK7ECSeoVvIf6CoL6eUjUNAe0cKwyWTASQqrn7sidUsmA_Fwc_BDli3X1fxndxEu_hY7Wd9Pw9FL9tNlk7Ulg_QfEJnzGFi07tncHQ_, gAAAAABmuVIfBLrQ6OjgV7NN34yk474n9rq7lnCn_LW0KJSw3y_uiL6hXiz5gHHBXguGwDjJv632DzftlBTkPV_w1VbqXDYUL5gJyXkF68Ld4g3aZTbluWw_, gAAAAABmuVIfL6S_WUQghhEW0QkiixHkVsG_of2gxN1JEJ7mwq3Kz58VNgm6frgxTms7Q_D8_U4SAQlENE3x9XI2zASbCstMd1qTYd9vDJUWZivSb7cOPp4_, gAAAAABmuVIffftG1vYYb9Xriv_NpU8cL2PAIYxWM0pIyYB99BLjhrvaXiXKn4ny7BC7yqsxYvcRChoXqHz2eVdAJ9dNV2EKWgxiAau2eyA7sp_WZ3bZ_p4_, gAAAAABmuVIfcJJ36pcvWvwZ4AvUrDnMqNaJjQhhOL73MngXzH5gCexj5ACCAiwJ6ZBYbf8xO_fGQ63WLtfgLJ3zkdAw117zBQ__)

def _sanitize_string(text: str, *, tab_width: int=8, convert_whitespace: bool=True) -> list[str]:
    """Return a list of one-line strings with tabs expanded, no newlines, and
    trailing whitespace stripped.

    Each tab is expanded with between 1 and `tab_width` spaces, so that the
    next character's index becomes a multiple of `tab_width` (8 by default).

    :param text: a multi-line string.
    :param tab_width: the number of spaces to replace tabs with.
    :param convert_whitespace: convert form feeds and vertical tabs to spaces?
    """
    if convert_whitespace:
        text = re.sub('[\x0b\x0c]', ' ', text)
    return [s.expandtabs(tab_width).rstrip() for s in text.splitlines()]

def parse_string(text: str, *, source_key: str | None=None, tab_width: int=8, offset_char: int=0) -> tuple[ElementListBase, DiagnosticList]:
    """Parse a multi-line string and return a list of elements.

    :param text: a multi-line string.
    :param tab_width: the number of spaces to replace tabs with.
    """
    context = gAAAAABmuVIfanHDr_DkOsfdtlLwNVSLjxE_lmhdlo_dWcJ6jNpVRkjsuu9j2TJrRXBxJ_CvimAiNYWtIjjwYJ3Cc0rn35_H1w__(_DEFAULT_BLOCK_PARSERS)
    lines = _sanitize_string(text, tab_width=tab_width)
    slice = gAAAAABmuVIfn8_QoZZda_B1ee7ZSZOU9HYQ3WCA_RfcyKsUPfTrulwxfbLz_wAf1h3l5WJTwf8xOwzWW1SaFPNclPosK0zq7A__([gAAAAABmuVIf9wRDJEScCUZq7RJd1lzU5Co9Q9qvdG39lzIABLH4JrYQUo0X7VYcijVx1kQa6sabviTFht6T3drJd4h3rsG6TA__(line, offset_line=i, offset_char=offset_char, source=source_key) for i, line in enumerate(lines)])
    return context.gAAAAABmuVIf9xwq70eSeWWPXDe93ixzBJC7a8weQ2_i_NZ9vZkDqYI2b0eXslg25raKyC1lEeLU9eMIiaFB8UWPp8wu9stR7g__(slice)