# coding: utf-8

"""
    Orbit Extrapolation API

    Orbit Extrapolation API

    The version of the OpenAPI document: 1.1.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spacetower_orbit_extrapolation_python_client.models.lof_based_maneuver_sequence import LofBasedManeuverSequence

class TestLofBasedManeuverSequence(unittest.TestCase):
    """LofBasedManeuverSequence unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LofBasedManeuverSequence:
        """Test LofBasedManeuverSequence
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LofBasedManeuverSequence`
        """
        model = LofBasedManeuverSequence()
        if include_optional:
            return LofBasedManeuverSequence(
                maneuver_sequence_type = 'IMPULSIVE_SEQUENCE'
            )
        else:
            return LofBasedManeuverSequence(
        )
        """

    def testLofBasedManeuverSequence(self):
        """Test LofBasedManeuverSequence"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
