# -*- coding: utf-8 -*-

"""
lob

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Size1Enum(object):

    """Implementation of the 'Size1' enum.

    The size of the card

    Attributes:
        ENUM_3375X2125: TODO: type description here.
        ENUM_2125X3375: TODO: type description here.

    """
    _all_values = ['3.375x2.125', '2.125x3.375']
    ENUM_3375X2125 = '3.375x2.125'

    ENUM_2125X3375 = '2.125x3.375'

    @classmethod
    def validate(cls, value):
        """Validates value contains in enum

        Args:
            value: the value to be validated

        Returns:
            boolean : if value is valid enum values.

        """
        return value in cls._all_values
   