# -*- coding: utf-8 -*-

"""
lob

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ThestatusofthecardEnum(object):

    """Implementation of the 'Thestatusofthecard.' enum.

    TODO: type enum description here.

    Attributes:
        PROCESSED: TODO: type description here.
        RENDERED: TODO: type description here.

    """
    _all_values = ['processed', 'rendered']
    PROCESSED = 'processed'

    RENDERED = 'rendered'

    @classmethod
    def validate(cls, value):
        """Validates value contains in enum

        Args:
            value: the value to be validated

        Returns:
            boolean : if value is valid enum values.

        """
        return value in cls._all_values
   