from robotkinematicscatalogue.inversekinematics.__6DOF.__UniversalRobots.UR3 import UR3
from robotkinematicscatalogue.inversekinematics.__6DOF.__UniversalRobots.UR5 import UR5
from robotkinematicscatalogue.inversekinematics.__6DOF.__UniversalRobots.UR5e import UR5e
from robotkinematicscatalogue.inversekinematics.__6DOF.__UniversalRobots.UR10 import UR10
from robotkinematicscatalogue.inversekinematics.__6DOF.__UniversalRobots.UR10e import UR10e
from robotkinematicscatalogue.inversekinematics.__6DOF.__UniversalRobots.UR16e import UR16e
from robotkinematicscatalogue.inversekinematics.__6DOF.__UniversalRobots.UR20 import UR20
from robotkinematicscatalogue.inversekinematics.__6DOF.__UniversalRobots.UR30 import UR30