# Generated by Django 4.2.11 on 2024-04-24 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panorama_openedx_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccessconfiguration',
            name='role',
            field=models.CharField(choices=[('READER', 'Reader'), ('AUTHOR', 'Author'), ('AI_AUTHOR', 'AI Author')], default='Reader', help_text='User role', max_length=20),
        ),
    ]
