# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/bundle.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import change_pb2 as proto_dot_change__pb2
from . import metadata_pb2 as proto_dot_metadata__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/bundle.proto',
  package='gink',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12proto/bundle.proto\x12\x04gink\x1a\x12proto/change.proto\x1a\x14proto/metadata.proto\"\xbc\x01\n\x06\x42undle\x12 \n\x08metadata\x18\x01 \x01(\x0b\x32\x0e.gink.Metadata\x12*\n\x07\x63hanges\x18\x02 \x03(\x0b\x32\x19.gink.Bundle.ChangesEntry\x12\x12\n\nverify_key\x18\x03 \x01(\x0c\x12\x12\n\nprior_hash\x18\x04 \x01(\x0c\x1a<\n\x0c\x43hangesEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\x1b\n\x05value\x18\x02 \x01(\x0b\x32\x0c.gink.Change:\x02\x38\x01\x62\x06proto3'
  ,
  dependencies=[proto_dot_change__pb2.DESCRIPTOR,proto_dot_metadata__pb2.DESCRIPTOR,])




_BUNDLE_CHANGESENTRY = _descriptor.Descriptor(
  name='ChangesEntry',
  full_name='gink.Bundle.ChangesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='gink.Bundle.ChangesEntry.key', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='gink.Bundle.ChangesEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=199,
  serialized_end=259,
)

_BUNDLE = _descriptor.Descriptor(
  name='Bundle',
  full_name='gink.Bundle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='metadata', full_name='gink.Bundle.metadata', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='changes', full_name='gink.Bundle.changes', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='verify_key', full_name='gink.Bundle.verify_key', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='prior_hash', full_name='gink.Bundle.prior_hash', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_BUNDLE_CHANGESENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=259,
)

_BUNDLE_CHANGESENTRY.fields_by_name['value'].message_type = proto_dot_change__pb2._CHANGE
_BUNDLE_CHANGESENTRY.containing_type = _BUNDLE
_BUNDLE.fields_by_name['metadata'].message_type = proto_dot_metadata__pb2._METADATA
_BUNDLE.fields_by_name['changes'].message_type = _BUNDLE_CHANGESENTRY
DESCRIPTOR.message_types_by_name['Bundle'] = _BUNDLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Bundle = _reflection.GeneratedProtocolMessageType('Bundle', (_message.Message,), {

  'ChangesEntry' : _reflection.GeneratedProtocolMessageType('ChangesEntry', (_message.Message,), {
    'DESCRIPTOR' : _BUNDLE_CHANGESENTRY,
    '__module__' : 'proto.bundle_pb2'
    # @@protoc_insertion_point(class_scope:gink.Bundle.ChangesEntry)
    })
  ,
  'DESCRIPTOR' : _BUNDLE,
  '__module__' : 'proto.bundle_pb2'
  # @@protoc_insertion_point(class_scope:gink.Bundle)
  })
_sym_db.RegisterMessage(Bundle)
_sym_db.RegisterMessage(Bundle.ChangesEntry)


_BUNDLE_CHANGESENTRY._options = None
# @@protoc_insertion_point(module_scope)
