from ._const import *


class TRTBuilderFlag(Enum):
    FP16 = 0
    INT8 = 1
    DEBUG = 2
    GPU_FALLBACK = 3
    STRICT_TYPES = 4
    REFIT = 5
    DISABLE_TIMING_CACHE = 6
    TF32 = 7
    SPARSE_WEIGHTS = 8
    SAFETY_SCOPE = 9
    OBEY_PRECISION_CONSTRAINTS = 10
    PREFER_PRECISION_CONSTRAINTS = 11
    DIRECT_IO = 12
    REJECT_EMPTY_ALGORITHMS = 13
    ENABLE_TACTIC_HEURISTIC = 14
    VERSION_COMPATIBLE = 15
    EXCLUDE_LEAN_RUNTIME = 16
    FP8 = 17
