import pandas as pd

class SubscribeCoveredWarrantEvents:
    def __init__(self, access_token: str, tickers: list, callback: callable) -> None: ...

    def start(self) -> None: ...
        
    def stop(self) -> None: ...

