import pandas as pd


class SubscribeTickerEvents:
    def __init__(self, access_token: str, tickers: list, callback: callable) -> None:
        self.tickers: list
        self.callback: callback
        self._stop: bool

    # def _data_handler(self, message) -> None: ...
        
    # def _build_connection(self) -> _build_connection: ...

    # def _receive_message(self, message) -> None: ...

    # def _handle_error(self, error) -> None: ...
    
    # def _on_connect(self) -> None: ...

    # def _on_disconnect(self) -> None: ... 

    # def _join_groups(self) -> None: ...
    # def _run(self) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...


