# coding: utf-8

"""
    Odin

    ODIN APIs to search across IP Services, CVEs, Certificates, Exposed Files/Buckets, Domains and more  # noqa: E501

    OpenAPI spec version: 1.0

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import odin
from odin.models.dns_api_response import DnsAPIResponse  # noqa: E501
from odin.rest import ApiException


class TestDnsAPIResponse(unittest.TestCase):
    """DnsAPIResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDnsAPIResponse(self):
        """Test DnsAPIResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = odin.models.dns_api_response.DnsAPIResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
