# Generated by Django 2.0.8 on 2018-08-15 09:02

import pretalx_com.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("pretalx_com", "0003_auto_20180814_1513")]

    operations = [
        migrations.AddField(
            model_name="eventcominvoice",
            name="secret",
            field=models.CharField(
                default=pretalx_com.models.generate_secret, max_length=32
            ),
        ),
        migrations.AlterField(
            model_name="eventcominvoice",
            name="invoice",
            field=models.FileField(upload_to=pretalx_com.models.invoice_path),
        ),
    ]
