# Generated by Django 2.1.2 on 2018-11-01 23:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("pretalx_com", "0006_auto_20181101_1747")]

    operations = [
        migrations.AlterModelOptions(
            name="blogpost", options={"ordering": ("-published",)}
        )
    ]
