# Generated by Django 2.1.5 on 2019-01-26 13:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("pretalx_com", "0007_auto_20181101_1857")]

    operations = [
        migrations.RemoveField(model_name="eventcomprofile", name="was_reviewed")
    ]
