# Generated by Django 2.2.1 on 2019-05-31 19:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("pretalx_com", "0009_eventcomprofile_contact_info")]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="is_draft",
            field=models.BooleanField(default=False),
        )
    ]
