# Generated by Django 2.2.4 on 2019-09-26 15:33

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0021_auto_20190429_0750"),
        ("pretalx_com", "0011_auto_20190702_0728"),
    ]

    operations = [
        migrations.CreateModel(
            name="DJCRMOrganiser",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                (
                    "nr",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=190)),
                (
                    "address_name",
                    models.CharField(blank=True, default="", max_length=190),
                ),
                (
                    "address_company",
                    models.CharField(blank=True, default="", max_length=190),
                ),
                (
                    "address_supplement",
                    models.CharField(blank=True, default="", max_length=190),
                ),
                (
                    "address_street",
                    models.CharField(blank=True, default="", max_length=190),
                ),
                (
                    "address_zipcode",
                    models.CharField(blank=True, default="", max_length=190),
                ),
                (
                    "address_city",
                    models.CharField(blank=True, default="", max_length=190),
                ),
                (
                    "address_country",
                    django_countries.fields.CountryField(
                        default="DE", max_length=2, verbose_name="Country"
                    ),
                ),
                ("language", models.CharField(default="de", max_length=50)),
                (
                    "organiser",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="event.Organiser",
                        related_name="djcrm",
                    ),
                ),
            ],
        )
    ]
