# Generated by Django 2.2.8 on 2020-01-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pretalx_com", "0014_pretalxinstance_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="djcrmorganiser",
            name="dsgvo_document",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
