# Generated by Django 2.2.9 on 2020-02-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pretalx_com", "0016_auto_20200117_1016"),
    ]

    operations = [
        migrations.AddField(
            model_name="pretalxinstance",
            name="known_events_data",
            field=models.TextField(blank=True, null=True),
        ),
    ]
