# Generated by Django 3.1.4 on 2021-05-18 14:04

import pretalx_com.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pretalx_com", "0018_organisercomprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="image",
            field=models.FileField(max_length=240, null=True, upload_to="com/blog/"),
        ),
        migrations.AlterField(
            model_name="djcrmorganiser",
            name="dsgvo_document",
            field=models.FileField(
                max_length=240, null=True, upload_to=pretalx_com.models.dsgvo_path
            ),
        ),
        migrations.AlterField(
            model_name="eventcominvoice",
            name="invoice",
            field=models.FileField(
                max_length=240, upload_to=pretalx_com.models.invoice_path
            ),
        ),
    ]
