# Generated by Django 4.2.4 on 2023-09-07 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pretalx_com", "0020_eventcominvoice_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="PretalxInstanceEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("slug", models.CharField(max_length=200)),
                ("name", models.CharField(null=True, max_length=200)),
                ("date_from", models.DateField(blank=True, null=True)),
                ("date_to", models.DateField(blank=True, null=True)),
                ("timezone", models.CharField(null=True, max_length=200)),
                ("base_url", models.CharField(null=True, max_length=200)),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="pretalx_com.pretalxinstance",
                    ),
                ),
            ],
        ),
    ]
