# Generated by Django 4.2.4 on 2023-09-11 13:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pretalx_com", "0022_pretalxinstanceevent_ignored"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pretalxinstance",
            name="known_events_data",
        ),
    ]
