# Generated by Django 4.2.4 on 2023-10-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pretalx_com", "0028_rename_aggreed_price_eventcomprofile_agreed_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="pretalxinstance",
            name="error_count",
            field=models.IntegerField(default=0),
        ),
    ]
