# Generated by Django 4.2.9 on 2024-03-14 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pretalx_com", "0031_pretalxinstance_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisercomprofile",
            name="discount",
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
