# coding: utf-8

"""
    Artifacts API

     Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 

    The version of the OpenAPI document: 1.6
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pyartifactsmmo.models.data_page_map_schema import DataPageMapSchema

class TestDataPageMapSchema(unittest.TestCase):
    """DataPageMapSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DataPageMapSchema:
        """Test DataPageMapSchema
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DataPageMapSchema`
        """
        model = DataPageMapSchema()
        if include_optional:
            return DataPageMapSchema(
                data = [
                    pyartifactsmmo.models.map_schema.MapSchema(
                        name = '', 
                        skin = '', 
                        x = 56, 
                        y = 56, 
                        content = pyartifactsmmo.models.map_content_schema.MapContentSchema(
                            type = '', 
                            code = '', ), )
                    ],
                total = 0.0,
                page = 1.0,
                size = 1.0,
                pages = 0.0
            )
        else:
            return DataPageMapSchema(
                data = [
                    pyartifactsmmo.models.map_schema.MapSchema(
                        name = '', 
                        skin = '', 
                        x = 56, 
                        y = 56, 
                        content = pyartifactsmmo.models.map_content_schema.MapContentSchema(
                            type = '', 
                            code = '', ), )
                    ],
                total = 0.0,
                page = 1.0,
                size = 1.0,
        )
        """

    def testDataPageMapSchema(self):
        """Test DataPageMapSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
