# coding: utf-8

"""
    Artifacts API

     Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 

    The version of the OpenAPI document: 1.6
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pyartifactsmmo.models.data_page_monster_schema import DataPageMonsterSchema

class TestDataPageMonsterSchema(unittest.TestCase):
    """DataPageMonsterSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DataPageMonsterSchema:
        """Test DataPageMonsterSchema
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DataPageMonsterSchema`
        """
        model = DataPageMonsterSchema()
        if include_optional:
            return DataPageMonsterSchema(
                data = [
                    pyartifactsmmo.models.monster_schema.MonsterSchema(
                        name = '', 
                        code = '', 
                        level = 56, 
                        hp = 56, 
                        attack_fire = 56, 
                        attack_earth = 56, 
                        attack_water = 56, 
                        attack_air = 56, 
                        res_fire = 56, 
                        res_earth = 56, 
                        res_water = 56, 
                        res_air = 56, 
                        min_gold = 56, 
                        max_gold = 56, 
                        drops = [
                            pyartifactsmmo.models.drop_rate_schema.DropRateSchema(
                                code = 'z', 
                                rate = 1.0, 
                                min_quantity = 1.0, 
                                max_quantity = 1.0, )
                            ], )
                    ],
                total = 0.0,
                page = 1.0,
                size = 1.0,
                pages = 0.0
            )
        else:
            return DataPageMonsterSchema(
                data = [
                    pyartifactsmmo.models.monster_schema.MonsterSchema(
                        name = '', 
                        code = '', 
                        level = 56, 
                        hp = 56, 
                        attack_fire = 56, 
                        attack_earth = 56, 
                        attack_water = 56, 
                        attack_air = 56, 
                        res_fire = 56, 
                        res_earth = 56, 
                        res_water = 56, 
                        res_air = 56, 
                        min_gold = 56, 
                        max_gold = 56, 
                        drops = [
                            pyartifactsmmo.models.drop_rate_schema.DropRateSchema(
                                code = 'z', 
                                rate = 1.0, 
                                min_quantity = 1.0, 
                                max_quantity = 1.0, )
                            ], )
                    ],
                total = 0.0,
                page = 1.0,
                size = 1.0,
        )
        """

    def testDataPageMonsterSchema(self):
        """Test DataPageMonsterSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
