# Generated by Django 3.1 on 2023-07-03 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_order', '0002_auto_20230703_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='RobokassaInvoice',
            fields=[
                ('baseinvoice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='garpix_order.baseinvoice')),
            ],
            options={
                'verbose_name': 'Платеж Robokassa',
                'verbose_name_plural': 'Платежи Robokassa',
            },
            bases=('garpix_order.baseinvoice',),
        ),
    ]
