from setuptools import find_packages, setup

setup(
    name="qenapy",
    version="0.0.11",
    description="This is Qena's microservice library",
    author="Naol Arega",
    author_email="narega@qena.dev",
    url="https://github.com/abrsh4/qenapy.git",
    packages=find_packages(),
    include_package_data=True,
    zip_safe=False,
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    install_requires=[
        "anyio==4.0.0; python_version >= '3.8'",
        "bcrypt==4.0.1",
        "certifi==2023.7.22; python_version >= '3.6'",
        "cffi==1.16.0; python_version >= '3.8'",
        "click==8.1.7; python_version >= '3.7'",
        "cronsim==2.3; python_version >= '3.7'",
        "cryptography==41.0.5",
        "dnspython==2.4.2; python_version >= '3.8' and python_version < '4.0'",
        "ecdsa==0.18.0; python_version >= '2.6' and python_version not in '3.0, 3.1, 3.2, 3.3'",
        "email-validator==2.1.0.post1",
        "exceptiongroup==1.1.3; python_version < '3.11'",
        "fastapi[all]==0.87.0; python_version >= '3.7'",
        "gunicorn==20.1.0; python_version >= '3.5'",
        "h11==0.14.0; python_version >= '3.7'",
        "httpcore==1.0.2; python_version >= '3.8'",
        "httptools==0.6.1",
        "httpx==0.25.1",
        "idna==3.4; python_version >= '3.5'",
        "itsdangerous==2.1.2",
        "jinja2==3.1.2",
        "markupsafe==2.1.3; python_version >= '3.7'",
        "motor==3.0.0; python_version >= '3.7'",
        "orjson==3.9.10",
        "passlib[bcrypt]==1.7.4",
        "pika==1.3.0",
        "pyasn1==0.5.0; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3, 3.4, 3.5'",
        "pycparser==2.21",
        "pydantic==1.10.13; python_version >= '3.7'",
        "pymongo==4.6.0; python_version >= '3.7'",
        "python-dotenv==1.0.0",
        "python-jose[cryptography]==3.3.0",
        "python-multipart==0.0.6",
        "pyyaml==6.0.1",
        "rsa==4.9; python_version >= '3.6' and python_version < '4'",
        "setuptools==68.2.2; python_version >= '3.8'",
        "six==1.16.0; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3'",
        "sniffio==1.3.0; python_version >= '3.7'",
        "starlette==0.21.0; python_version >= '3.7'",
        "typing-extensions==4.8.0; python_version >= '3.8'",
        "ujson==5.8.0",
        "uvicorn[standard]==0.24.0.post1",
        "uvloop==0.19.0",
        "watchfiles==0.21.0",
        "websockets==12.0",
    ],
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    python_requires=">=3.6",
)
