"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import more_than_inference.protos.node_pb2
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class Resource(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CPU_FIELD_NUMBER: builtins.int
    RAM_FIELD_NUMBER: builtins.int
    GPU_FIELD_NUMBER: builtins.int
    VRAM_FIELD_NUMBER: builtins.int
    NODE_FIELD_NUMBER: builtins.int
    CPU: builtins.int
    RAM: builtins.int
    GPU: builtins.int
    VRAM: builtins.int
    @property
    def node(self) -> more_than_inference.protos.node_pb2.Node: ...
    def __init__(
        self,
        *,
        CPU: builtins.int = ...,
        RAM: builtins.int = ...,
        GPU: builtins.int = ...,
        VRAM: builtins.int = ...,
        node: more_than_inference.protos.node_pb2.Node | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["node", b"node"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["CPU", b"CPU", "GPU", b"GPU", "RAM", b"RAM", "VRAM", b"VRAM", "node", b"node"]) -> None: ...

global___Resource = Resource

@typing_extensions.final
class Apply(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACCEPT_FIELD_NUMBER: builtins.int
    ENV_FIELD_NUMBER: builtins.int
    Accept: builtins.bool
    Env: builtins.str
    def __init__(
        self,
        *,
        Accept: builtins.bool = ...,
        Env: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["Accept", b"Accept", "Env", b"Env"]) -> None: ...

global___Apply = Apply
