# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: more_than_inference/protos/pipeline.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from more_than_inference.protos import node_pb2 as more__than__inference_dot_protos_dot_node__pb2
from more_than_inference.protos import data_pb2 as more__than__inference_dot_protos_dot_data__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)more_than_inference/protos/pipeline.proto\x12\x08pipeline\x1a%more_than_inference/protos/node.proto\x1a%more_than_inference/protos/data.proto\"P\n\x08Pipeline\x12\x0b\n\x03Key\x18\x01 \x01(\t\x12\x1d\n\tStackList\x18\x02 \x03(\x0b\x32\n.node.Node\x12\x18\n\x04\x44\x61ta\x18\x03 \x01(\x0b\x32\n.data.Datab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'more_than_inference.protos.pipeline_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PIPELINE']._serialized_start=133
  _globals['_PIPELINE']._serialized_end=213
# @@protoc_insertion_point(module_scope)
