
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-08-09T11:52:02+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "b80544097d821c281eda12102f7918e013266dde",
 "version": "1.5.14.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
