# Generated by Django 4.2.11 on 2024-04-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panorama_openedx_backend', '0002_useraccessconfiguration_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='panorama_config',
        ),
        migrations.AlterField(
            model_name='useraccessconfiguration',
            name='arn',
            field=models.CharField(default='', help_text='Quicksight user ARN', max_length=255, verbose_name='ARN'),
        ),
    ]
