GEM_MIGRATIONS_MODULE_NAME = "gem_migrations"
GEM_MIGRATIONS_STABLE_INDEX_FILE_NAME = "stable.json"
GEM_MIGRATIONS_INITIAL_MIGRATION_FILE_NAME = "initial.json"
GEM_MIGRATIONS_MIGRATION_FILE_PREFIX = "migrategem_"
