
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-08-08T12:28:38-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "2052777c68084cbd6e9c7a33151f92b420ac6b85",
 "version": "0.9.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
