# coding: utf-8

"""
    Artifacts API

     Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 

    The version of the OpenAPI document: 1.6
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pyartifactsmmo.models.character_schema import CharacterSchema

class TestCharacterSchema(unittest.TestCase):
    """CharacterSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CharacterSchema:
        """Test CharacterSchema
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CharacterSchema`
        """
        model = CharacterSchema()
        if include_optional:
            return CharacterSchema(
                name = '',
                skin = 'men1',
                level = 56,
                xp = 56,
                max_xp = 56,
                total_xp = 56,
                gold = 56,
                speed = 56,
                mining_level = 56,
                mining_xp = 56,
                mining_max_xp = 56,
                woodcutting_level = 56,
                woodcutting_xp = 56,
                woodcutting_max_xp = 56,
                fishing_level = 56,
                fishing_xp = 56,
                fishing_max_xp = 56,
                weaponcrafting_level = 56,
                weaponcrafting_xp = 56,
                weaponcrafting_max_xp = 56,
                gearcrafting_level = 56,
                gearcrafting_xp = 56,
                gearcrafting_max_xp = 56,
                jewelrycrafting_level = 56,
                jewelrycrafting_xp = 56,
                jewelrycrafting_max_xp = 56,
                cooking_level = 56,
                cooking_xp = 56,
                cooking_max_xp = 56,
                hp = 56,
                haste = 56,
                critical_strike = 56,
                stamina = 56,
                attack_fire = 56,
                attack_earth = 56,
                attack_water = 56,
                attack_air = 56,
                dmg_fire = 56,
                dmg_earth = 56,
                dmg_water = 56,
                dmg_air = 56,
                res_fire = 56,
                res_earth = 56,
                res_water = 56,
                res_air = 56,
                x = 56,
                y = 56,
                cooldown = 56,
                cooldown_expiration = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                weapon_slot = '',
                shield_slot = '',
                helmet_slot = '',
                body_armor_slot = '',
                leg_armor_slot = '',
                boots_slot = '',
                ring1_slot = '',
                ring2_slot = '',
                amulet_slot = '',
                artifact1_slot = '',
                artifact2_slot = '',
                artifact3_slot = '',
                consumable1_slot = '',
                consumable1_slot_quantity = 56,
                consumable2_slot = '',
                consumable2_slot_quantity = 56,
                task = '',
                task_type = '',
                task_progress = 56,
                task_total = 56,
                inventory_max_items = 56,
                inventory = [
                    pyartifactsmmo.models.inventory_slot.InventorySlot(
                        slot = 56, 
                        code = '', 
                        quantity = 56, )
                    ]
            )
        else:
            return CharacterSchema(
                name = '',
                skin = 'men1',
                level = 56,
                xp = 56,
                max_xp = 56,
                total_xp = 56,
                gold = 56,
                speed = 56,
                mining_level = 56,
                mining_xp = 56,
                mining_max_xp = 56,
                woodcutting_level = 56,
                woodcutting_xp = 56,
                woodcutting_max_xp = 56,
                fishing_level = 56,
                fishing_xp = 56,
                fishing_max_xp = 56,
                weaponcrafting_level = 56,
                weaponcrafting_xp = 56,
                weaponcrafting_max_xp = 56,
                gearcrafting_level = 56,
                gearcrafting_xp = 56,
                gearcrafting_max_xp = 56,
                jewelrycrafting_level = 56,
                jewelrycrafting_xp = 56,
                jewelrycrafting_max_xp = 56,
                cooking_level = 56,
                cooking_xp = 56,
                cooking_max_xp = 56,
                hp = 56,
                haste = 56,
                critical_strike = 56,
                stamina = 56,
                attack_fire = 56,
                attack_earth = 56,
                attack_water = 56,
                attack_air = 56,
                dmg_fire = 56,
                dmg_earth = 56,
                dmg_water = 56,
                dmg_air = 56,
                res_fire = 56,
                res_earth = 56,
                res_water = 56,
                res_air = 56,
                x = 56,
                y = 56,
                cooldown = 56,
                weapon_slot = '',
                shield_slot = '',
                helmet_slot = '',
                body_armor_slot = '',
                leg_armor_slot = '',
                boots_slot = '',
                ring1_slot = '',
                ring2_slot = '',
                amulet_slot = '',
                artifact1_slot = '',
                artifact2_slot = '',
                artifact3_slot = '',
                consumable1_slot = '',
                consumable1_slot_quantity = 56,
                consumable2_slot = '',
                consumable2_slot_quantity = 56,
                task = '',
                task_type = '',
                task_progress = 56,
                task_total = 56,
                inventory_max_items = 56,
        )
        """

    def testCharacterSchema(self):
        """Test CharacterSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
