# coding: utf-8

"""
    Artifacts API

     Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 

    The version of the OpenAPI document: 1.6
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pyartifactsmmo.models.equipment_response_schema import EquipmentResponseSchema

class TestEquipmentResponseSchema(unittest.TestCase):
    """EquipmentResponseSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EquipmentResponseSchema:
        """Test EquipmentResponseSchema
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EquipmentResponseSchema`
        """
        model = EquipmentResponseSchema()
        if include_optional:
            return EquipmentResponseSchema(
                data = pyartifactsmmo.models.equip_request_schema.EquipRequestSchema(
                    cooldown = null, 
                    slot = 'weapon', 
                    item = null, 
                    character = null, )
            )
        else:
            return EquipmentResponseSchema(
                data = pyartifactsmmo.models.equip_request_schema.EquipRequestSchema(
                    cooldown = null, 
                    slot = 'weapon', 
                    item = null, 
                    character = null, ),
        )
        """

    def testEquipmentResponseSchema(self):
        """Test EquipmentResponseSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
