
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-08-11T21:30:04-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "78775485cf2ddd8fbd6250b44775352b1ff915a4",
 "version": "0.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
