# coding: utf-8

"""
    Orbit Extrapolation API

    Orbit Extrapolation API

    The version of the OpenAPI document: 1.1.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class LofType(str, Enum):
    """
    LofType
    """

    """
    allowed enum values
    """
    TNW = 'TNW'
    QSW = 'QSW'
    LVLH_CCSDS = 'LVLH_CCSDS'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of LofType from a JSON string"""
        return cls(json.loads(json_str))


