# -*- coding: utf-8 -*-

"""
lob

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class AddressCountry2Enum(object):

    """Implementation of the 'AddressCountry2' enum.

    TODO: type enum description here.

    Attributes:
        US: TODO: type description here.

    """
    _all_values = ['US']
    US = 'US'

    @classmethod
    def validate(cls, value):
        """Validates value contains in enum

        Args:
            value: the value to be validated

        Returns:
            boolean : if value is valid enum values.

        """
        return value in cls._all_values
   