# -*- coding: utf-8 -*-

"""
lob

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Case1Enum(object):

    """Implementation of the 'case1' enum.

    Casing of the verified address. Possible values are `upper` and `proper`
    for uppercased (e.g. "PO BOX") and proper-cased (e.g. "PO Box"),
    respectively. Only affects `primary_line`, `city`, and `state`. Default
    casing is `upper`.

    Attributes:
        UPPER: TODO: type description here.
        PROPER: TODO: type description here.

    """
    UPPER = 'upper'

    PROPER = 'proper'

