# -*- coding: utf-8 -*-

"""
lob

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class CmpScheduleTypeEnum(object):

    """Implementation of the 'cmp_schedule_type' enum.

    How the campaign should be scheduled. Only value available today is
    `immediate`.

    Attributes:
        IMMEDIATE: TODO: type description here.

    """
    IMMEDIATE = 'immediate'

