# -*- coding: utf-8 -*-

"""
lob

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class CountryExtendedEnum(object):

    """Implementation of the 'country_extended' enum.

    Must be a 2 letter country short-name code (ISO 3166). Does not accept
    `US`, `AS`, `PR`, `FM`, `GU`, `MH`, `MP`, `PW`, or `VI`. For these
    addresses, please use the US verification API. Also does not accept `PS`,
    which is not currently supported.

    Attributes:
        AD: TODO: type description here.
        AE: TODO: type description here.
        AF: TODO: type description here.
        AG: TODO: type description here.
        AI: TODO: type description here.
        AL: TODO: type description here.
        AN: TODO: type description here.
        AO: TODO: type description here.
        AQ: TODO: type description here.
        AR: TODO: type description here.
        AT: TODO: type description here.
        AU: TODO: type description here.
        AW: TODO: type description here.
        AZ: TODO: type description here.
        BA: TODO: type description here.
        BB: TODO: type description here.
        BD: TODO: type description here.
        BE: TODO: type description here.
        BF: TODO: type description here.
        BG: TODO: type description here.
        BH: TODO: type description here.
        BI: TODO: type description here.
        BJ: TODO: type description here.
        BM: TODO: type description here.
        BN: TODO: type description here.
        BO: TODO: type description here.
        BQ: TODO: type description here.
        BR: TODO: type description here.
        BS: TODO: type description here.
        BT: TODO: type description here.
        BW: TODO: type description here.
        BY: TODO: type description here.
        BZ: TODO: type description here.
        CA: TODO: type description here.
        CD: TODO: type description here.
        CG: TODO: type description here.
        CH: TODO: type description here.
        CI: TODO: type description here.
        CK: TODO: type description here.
        CL: TODO: type description here.
        CM: TODO: type description here.
        CN: TODO: type description here.
        CO: TODO: type description here.
        CR: TODO: type description here.
        CS: TODO: type description here.
        CU: TODO: type description here.
        CV: TODO: type description here.
        CW: TODO: type description here.
        CY: TODO: type description here.
        CZ: TODO: type description here.
        DE: TODO: type description here.
        DJ: TODO: type description here.
        DK: TODO: type description here.
        DM: TODO: type description here.
        DO: TODO: type description here.
        DZ: TODO: type description here.
        EC: TODO: type description here.
        EE: TODO: type description here.
        EG: TODO: type description here.
        EH: TODO: type description here.
        ER: TODO: type description here.
        ES: TODO: type description here.
        ET: TODO: type description here.
        FI: TODO: type description here.
        FJ: TODO: type description here.
        FK: TODO: type description here.
        FO: TODO: type description here.
        FR: TODO: type description here.
        GA: TODO: type description here.
        GB: TODO: type description here.
        GD: TODO: type description here.
        GE: TODO: type description here.
        GH: TODO: type description here.
        GI: TODO: type description here.
        GL: TODO: type description here.
        GM: TODO: type description here.
        GN: TODO: type description here.
        GQ: TODO: type description here.
        GR: TODO: type description here.
        GS: TODO: type description here.
        GT: TODO: type description here.
        GW: TODO: type description here.
        GY: TODO: type description here.
        HK: TODO: type description here.
        HN: TODO: type description here.
        HR: TODO: type description here.
        HT: TODO: type description here.
        HU: TODO: type description here.
        ID: TODO: type description here.
        IE: TODO: type description here.
        IL: TODO: type description here.
        IN: TODO: type description here.
        IO: TODO: type description here.
        IQ: TODO: type description here.
        IR: TODO: type description here.
        IS: TODO: type description here.
        IT: TODO: type description here.
        JM: TODO: type description here.
        JO: TODO: type description here.
        JP: TODO: type description here.
        KE: TODO: type description here.
        KG: TODO: type description here.
        KH: TODO: type description here.
        KI: TODO: type description here.
        KM: TODO: type description here.
        KN: TODO: type description here.
        KP: TODO: type description here.
        KR: TODO: type description here.
        KW: TODO: type description here.
        KY: TODO: type description here.
        KZ: TODO: type description here.
        LA: TODO: type description here.
        LB: TODO: type description here.
        LC: TODO: type description here.
        LI: TODO: type description here.
        LK: TODO: type description here.
        LR: TODO: type description here.
        LS: TODO: type description here.
        LT: TODO: type description here.
        LU: TODO: type description here.
        LV: TODO: type description here.
        LY: TODO: type description here.
        MA: TODO: type description here.
        MC: TODO: type description here.
        MD: TODO: type description here.
        ME: TODO: type description here.
        MG: TODO: type description here.
        MK: TODO: type description here.
        ML: TODO: type description here.
        MM: TODO: type description here.
        MN: TODO: type description here.
        MO: TODO: type description here.
        MR: TODO: type description here.
        MS: TODO: type description here.
        MT: TODO: type description here.
        MU: TODO: type description here.
        MV: TODO: type description here.
        MW: TODO: type description here.
        MX: TODO: type description here.
        MY: TODO: type description here.
        MZ: TODO: type description here.
        NA: TODO: type description here.
        NE: TODO: type description here.
        NF: TODO: type description here.
        NG: TODO: type description here.
        NI: TODO: type description here.
        NL: TODO: type description here.
        NO: TODO: type description here.
        NP: TODO: type description here.
        NR: TODO: type description here.
        NU: TODO: type description here.
        NZ: TODO: type description here.
        OM: TODO: type description here.
        PA: TODO: type description here.
        PE: TODO: type description here.
        PG: TODO: type description here.
        PH: TODO: type description here.
        PK: TODO: type description here.
        PL: TODO: type description here.
        PN: TODO: type description here.
        PT: TODO: type description here.
        PY: TODO: type description here.
        QA: TODO: type description here.
        RO: TODO: type description here.
        RS: TODO: type description here.
        RU: TODO: type description here.
        RW: TODO: type description here.
        SA: TODO: type description here.
        SB: TODO: type description here.
        SC: TODO: type description here.
        SD: TODO: type description here.
        SE: TODO: type description here.
        SG: TODO: type description here.
        SH: TODO: type description here.
        SI: TODO: type description here.
        SK: TODO: type description here.
        SL: TODO: type description here.
        SM: TODO: type description here.
        SN: TODO: type description here.
        SO: TODO: type description here.
        SR: TODO: type description here.
        SS: TODO: type description here.
        ST: TODO: type description here.
        SV: TODO: type description here.
        SX: TODO: type description here.
        SY: TODO: type description here.
        SZ: TODO: type description here.
        TC: TODO: type description here.
        TD: TODO: type description here.
        TG: TODO: type description here.
        TH: TODO: type description here.
        TJ: TODO: type description here.
        TK: TODO: type description here.
        TL: TODO: type description here.
        TM: TODO: type description here.
        TN: TODO: type description here.
        TO: TODO: type description here.
        TR: TODO: type description here.
        TT: TODO: type description here.
        TV: TODO: type description here.
        TW: TODO: type description here.
        TZ: TODO: type description here.
        UA: TODO: type description here.
        UG: TODO: type description here.
        UY: TODO: type description here.
        UZ: TODO: type description here.
        VA: TODO: type description here.
        VC: TODO: type description here.
        VE: TODO: type description here.
        VG: TODO: type description here.
        VN: TODO: type description here.
        VU: TODO: type description here.
        WS: TODO: type description here.
        YE: TODO: type description here.
        ZA: TODO: type description here.
        ZM: TODO: type description here.
        ZW: TODO: type description here.

    """
    _all_values = ['AD', 'AE', 'AF', 'AG', 'AI', 'AL', 'AN', 'AO', 'AQ', 'AR', 'AT', 'AU', 'AW', 'AZ', 'BA', 'BB', 'BD', 'BE', 'BF', 'BG', 'BH', 'BI', 'BJ', 'BM', 'BN', 'BO', 'BQ', 'BR', 'BS', 'BT', 'BW', 'BY', 'BZ', 'CA', 'CD', 'CG', 'CH', 'CI', 'CK', 'CL', 'CM', 'CN', 'CO', 'CR', 'CS', 'CU', 'CV', 'CW', 'CY', 'CZ', 'DE', 'DJ', 'DK', 'DM', 'DO', 'DZ', 'EC', 'EE', 'EG', 'EH', 'ER', 'ES', 'ET', 'FI', 'FJ', 'FK', 'FO', 'FR', 'GA', 'GB', 'GD', 'GE', 'GH', 'GI', 'GL', 'GM', 'GN', 'GQ', 'GR', 'GS', 'GT', 'GW', 'GY', 'HK', 'HN', 'HR', 'HT', 'HU', 'ID', 'IE', 'IL', 'IN', 'IO', 'IQ', 'IR', 'IS', 'IT', 'JM', 'JO', 'JP', 'KE', 'KG', 'KH', 'KI', 'KM', 'KN', 'KP', 'KR', 'KW', 'KY', 'KZ', 'LA', 'LB', 'LC', 'LI', 'LK', 'LR', 'LS', 'LT', 'LU', 'LV', 'LY', 'MA', 'MC', 'MD', 'ME', 'MG', 'MK', 'ML', 'MM', 'MN', 'MO', 'MR', 'MS', 'MT', 'MU', 'MV', 'MW', 'MX', 'MY', 'MZ', 'NA', 'NE', 'NF', 'NG', 'NI', 'NL', 'NO', 'NP', 'NR', 'NU', 'NZ', 'OM', 'PA', 'PE', 'PG', 'PH', 'PK', 'PL', 'PN', 'PT', 'PY', 'QA', 'RO', 'RS', 'RU', 'RW', 'SA', 'SB', 'SC', 'SD', 'SE', 'SG', 'SH', 'SI', 'SK', 'SL', 'SM', 'SN', 'SO', 'SR', 'SS', 'ST', 'SV', 'SX', 'SY', 'SZ', 'TC', 'TD', 'TG', 'TH', 'TJ', 'TK', 'TL', 'TM', 'TN', 'TO', 'TR', 'TT', 'TV', 'TW', 'TZ', 'UA', 'UG', 'UY', 'UZ', 'VA', 'VC', 'VE', 'VG', 'VN', 'VU', 'WS', 'YE', 'ZA', 'ZM', 'ZW']
    AD = 'AD'

    AE = 'AE'

    AF = 'AF'

    AG = 'AG'

    AI = 'AI'

    AL = 'AL'

    AN = 'AN'

    AO = 'AO'

    AQ = 'AQ'

    AR = 'AR'

    AT = 'AT'

    AU = 'AU'

    AW = 'AW'

    AZ = 'AZ'

    BA = 'BA'

    BB = 'BB'

    BD = 'BD'

    BE = 'BE'

    BF = 'BF'

    BG = 'BG'

    BH = 'BH'

    BI = 'BI'

    BJ = 'BJ'

    BM = 'BM'

    BN = 'BN'

    BO = 'BO'

    BQ = 'BQ'

    BR = 'BR'

    BS = 'BS'

    BT = 'BT'

    BW = 'BW'

    BY = 'BY'

    BZ = 'BZ'

    CA = 'CA'

    CD = 'CD'

    CG = 'CG'

    CH = 'CH'

    CI = 'CI'

    CK = 'CK'

    CL = 'CL'

    CM = 'CM'

    CN = 'CN'

    CO = 'CO'

    CR = 'CR'

    CS = 'CS'

    CU = 'CU'

    CV = 'CV'

    CW = 'CW'

    CY = 'CY'

    CZ = 'CZ'

    DE = 'DE'

    DJ = 'DJ'

    DK = 'DK'

    DM = 'DM'

    DO = 'DO'

    DZ = 'DZ'

    EC = 'EC'

    EE = 'EE'

    EG = 'EG'

    EH = 'EH'

    ER = 'ER'

    ES = 'ES'

    ET = 'ET'

    FI = 'FI'

    FJ = 'FJ'

    FK = 'FK'

    FO = 'FO'

    FR = 'FR'

    GA = 'GA'

    GB = 'GB'

    GD = 'GD'

    GE = 'GE'

    GH = 'GH'

    GI = 'GI'

    GL = 'GL'

    GM = 'GM'

    GN = 'GN'

    GQ = 'GQ'

    GR = 'GR'

    GS = 'GS'

    GT = 'GT'

    GW = 'GW'

    GY = 'GY'

    HK = 'HK'

    HN = 'HN'

    HR = 'HR'

    HT = 'HT'

    HU = 'HU'

    ID = 'ID'

    IE = 'IE'

    IL = 'IL'

    IN = 'IN'

    IO = 'IO'

    IQ = 'IQ'

    IR = 'IR'

    IS = 'IS'

    IT = 'IT'

    JM = 'JM'

    JO = 'JO'

    JP = 'JP'

    KE = 'KE'

    KG = 'KG'

    KH = 'KH'

    KI = 'KI'

    KM = 'KM'

    KN = 'KN'

    KP = 'KP'

    KR = 'KR'

    KW = 'KW'

    KY = 'KY'

    KZ = 'KZ'

    LA = 'LA'

    LB = 'LB'

    LC = 'LC'

    LI = 'LI'

    LK = 'LK'

    LR = 'LR'

    LS = 'LS'

    LT = 'LT'

    LU = 'LU'

    LV = 'LV'

    LY = 'LY'

    MA = 'MA'

    MC = 'MC'

    MD = 'MD'

    ME = 'ME'

    MG = 'MG'

    MK = 'MK'

    ML = 'ML'

    MM = 'MM'

    MN = 'MN'

    MO = 'MO'

    MR = 'MR'

    MS = 'MS'

    MT = 'MT'

    MU = 'MU'

    MV = 'MV'

    MW = 'MW'

    MX = 'MX'

    MY = 'MY'

    MZ = 'MZ'

    NA = 'NA'

    NE = 'NE'

    NF = 'NF'

    NG = 'NG'

    NI = 'NI'

    NL = 'NL'

    NO = 'NO'

    NP = 'NP'

    NR = 'NR'

    NU = 'NU'

    NZ = 'NZ'

    OM = 'OM'

    PA = 'PA'

    PE = 'PE'

    PG = 'PG'

    PH = 'PH'

    PK = 'PK'

    PL = 'PL'

    PN = 'PN'

    PT = 'PT'

    PY = 'PY'

    QA = 'QA'

    RO = 'RO'

    RS = 'RS'

    RU = 'RU'

    RW = 'RW'

    SA = 'SA'

    SB = 'SB'

    SC = 'SC'

    SD = 'SD'

    SE = 'SE'

    SG = 'SG'

    SH = 'SH'

    SI = 'SI'

    SK = 'SK'

    SL = 'SL'

    SM = 'SM'

    SN = 'SN'

    SO = 'SO'

    SR = 'SR'

    SS = 'SS'

    ST = 'ST'

    SV = 'SV'

    SX = 'SX'

    SY = 'SY'

    SZ = 'SZ'

    TC = 'TC'

    TD = 'TD'

    TG = 'TG'

    TH = 'TH'

    TJ = 'TJ'

    TK = 'TK'

    TL = 'TL'

    TM = 'TM'

    TN = 'TN'

    TO = 'TO'

    TR = 'TR'

    TT = 'TT'

    TV = 'TV'

    TW = 'TW'

    TZ = 'TZ'

    UA = 'UA'

    UG = 'UG'

    UY = 'UY'

    UZ = 'UZ'

    VA = 'VA'

    VC = 'VC'

    VE = 'VE'

    VG = 'VG'

    VN = 'VN'

    VU = 'VU'

    WS = 'WS'

    YE = 'YE'

    ZA = 'ZA'

    ZM = 'ZM'

    ZW = 'ZW'

    @classmethod
    def validate(cls, value):
        """Validates value contains in enum

        Args:
            value: the value to be validated

        Returns:
            boolean : if value is valid enum values.

        """
        return value in cls._all_values
   