# -*- coding: utf-8 -*-

"""
lob

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ObjectEnum(object):

    """Implementation of the 'Object' enum.

    Value is resource type.

    Attributes:
        BILLING_GROUP: TODO: type description here.

    """
    BILLING_GROUP = 'billing_group'

