# -*- coding: utf-8 -*-

"""
lob

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ResourceEnum(object):

    """Implementation of the 'Resource' enum.

    TODO: type enum description here.

    Attributes:
        POSTCARDS: TODO: type description here.
        ENUM_SELF MAILERS: TODO: type description here.
        LETTERS: TODO: type description here.
        CHECKS: TODO: type description here.
        ADDRESSES: TODO: type description here.
        ENUM_BANK ACCOUNTS: TODO: type description here.

    """
    _all_values = ['postcards', 'self mailers', 'letters', 'checks', 'addresses', 'bank accounts']
    POSTCARDS = 'postcards'

    ENUM_SELF_MAILERS = 'self mailers'

    LETTERS = 'letters'

    CHECKS = 'checks'

    ADDRESSES = 'addresses'

    ENUM_BANK_ACCOUNTS = 'bank accounts'

    @classmethod
    def validate(cls, value):
        """Validates value contains in enum

        Args:
            value: the value to be validated

        Returns:
            boolean : if value is valid enum values.

        """
        return value in cls._all_values
   