# -*- coding: utf-8 -*-

"""
lob

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class XLangOutputEnum(object):

    """Implementation of the 'x-lang-output' enum.

    TODO: type enum description here.

    Attributes:
        NATIVE: TODO: type description here.
        MATCH: TODO: type description here.

    """
    NATIVE = 'native'

    MATCH = 'match'

