# Generated by Django 3.2.12 on 2022-03-09 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tezor', '0003_manual_invoicing'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'permissions': (('send_invoice_email', 'Can send invoice by email'),)},
        ),
    ]
