# Generated by Django 3.2.12 on 2022-03-20 21:51

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('tezor', '0008_always_set_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='billing_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
