# Generated by Django 4.2.10 on 2024-03-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tezor", "0010_alter_client_options_alter_invoice_options_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="client",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="invoicegroup",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="invoiceitem",
            managers=[],
        ),
        migrations.RemoveConstraint(
            model_name="client",
            name="uniq_client_per_site",
        ),
    ] + [
        migrations.RunSQL(
            f"ALTER TABLE tezor_{model_name} drop column if exists site_id;"
        ) for model_name  in
        [
            "client",
            "invoicegroup",
            "invoiceitem",
        ]
    ] + [
        migrations.AlterField(
            model_name="client",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="Name"),
        ),
    ]
