import pandas as pd

class SubscribeCoveredWarrantEvents:
    def __init__(self, access_token: str, tickers: list, callback: callable) -> None:
        # self.access_token: str
        self.tickers: list
        # self.url: str
        # self.hub_connection: self._build_connection
        # self.connected: bool 
        self.callback: callback
        # self.df: dict[str,pd.DataFrame]
        self._stop: bool
    # def _data_handler(self, message) -> None: ...
        
    # def _build_connection(self) -> _build_connection: ...

    # def _receive_message(self, message) -> None: ...

    # def _handle_error(self, error) -> None: ...
    
    # def _on_connect(self) -> None: ...

    # def _on_disconnect(self) -> None: ... 

    # def _join_groups(self) -> None: ...

    # def _run(self) -> None: ...
        
    def start(self) -> None: ...
        
    def stop(self) -> None: ...

