
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-08-09T18:03:26+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "3e7ed865c3b3de601c92edbd9744f2bff9054051",
 "version": "0.14.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
