def column_names():
    return [
        "GLADE no",
        "PGC no",
        "GWGC name",
        "HyperLEDA name",
        "2MASS name",
        "WISExSCOS name",
        "SDSS-DR16Q name",
        "Object type flag",
        "RA",
        "Dec",
        "B",
        "B_err",
        "B flag",
        "B_Abs",
        "J",
        "J_err",
        "H",
        "H_err",
        "K",
        "K_err",
        "W1",
        "W1_err",
        "W2",
        "W2_err",
        "W1 flag",
        "B_J",
        "B_J err",
        "z_helio",
        "z_cmb",
        "z flag",
        "v_err",
        "z_err",
        "d_L",
        "d_L err",
        "dist flag",
        "M*",
        "M*_err",
        "M* flag",
        "Merger rate",
        "Merger rate error",
    ]
