# Generated by Django 3.2.12 on 2022-03-14 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tezor', '0004_client_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='for_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='for_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
