# Generated by Django 4.2.11 on 2024-04-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panorama_openedx_backend', '0003_delete_panorama_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='priority',
            field=models.IntegerField(default=10, help_text='Order of appearance in the menu. The lower the number, the higher the position.'),
        ),
    ]
